[package]
name = "multigrind"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curve25519-dalek = { version = "3.2.1" }
fastrand = "2.0.1"
logfather = "0.2.3"
num-format = "0.4.4"
sha2 = "0.10.8"
